#!/bin/bash
#
# RKE2 Agent (Worker) Installation Script
# This script installs RKE2 agent on Amazon Linux 2023 (or compatible systems)
#
# Usage:
#   chmod +x install-rke2-agent.sh
#   sudo ./install-rke2-agent.sh <SERVER_IP> <TOKEN>
#
# Example:
#   sudo ./install-rke2-agent.sh 10.0.1.100 K10abcdef::server:abcdef123456
#
# Prerequisites:
#   - Amazon Linux 2023 or compatible Linux distribution
#   - Root or sudo access
#   - Internet connectivity
#   - Server IP and token from RKE2 server
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging function
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Check arguments
if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <SERVER_IP> <TOKEN>"
    echo ""
    echo "Arguments:"
    echo "  SERVER_IP  - IP address or hostname of RKE2 server (control plane)"
    echo "  TOKEN      - Node token from RKE2 server"
    echo ""
    echo "Example:"
    echo "  $0 10.0.1.100 K10abcdef::server:abcdef123456"
    echo ""
    echo "To get the token from server:"
    echo "  ssh ec2-user@<SERVER_IP> 'sudo cat /var/lib/rancher/rke2/server/node-token'"
    exit 1
fi

SERVER_IP=$1
TOKEN=$2

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   error "This script must be run as root. Use: sudo $0"
fi

log "Starting RKE2 agent installation..."
log "Server: $SERVER_IP"
log "Token: ${TOKEN:0:10}..."

# ============================================
# Step 1: Update System
# ============================================
log "Step 1: Updating system packages..."
if command -v dnf &> /dev/null; then
    dnf update -y
elif command -v yum &> /dev/null; then
    yum update -y
else
    warn "Neither dnf nor yum found. Skipping system update."
fi

# ============================================
# Step 2: Install Required Packages
# ============================================
log "Step 2: Installing required packages..."
PACKAGES="curl wget git conntrack socat nfs-utils iptables"

if command -v dnf &> /dev/null; then
    dnf install -y $PACKAGES
elif command -v yum &> /dev/null; then
    yum install -y $PACKAGES
fi

# ============================================
# Step 3: Configure Kernel Modules
# ============================================
log "Step 3: Configuring kernel modules..."

# Load modules
modprobe overlay || warn "Could not load overlay module"
modprobe br_netfilter || warn "Could not load br_netfilter module"

# Persist modules
cat <<EOF > /etc/modules-load.d/rke2.conf
overlay
br_netfilter
EOF

# ============================================
# Step 4: Configure Sysctl
# ============================================
log "Step 4: Configuring sysctl settings..."

cat <<EOF > /etc/sysctl.d/99-kubernetes.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

sysctl --system > /dev/null

# ============================================
# Step 5: Disable Swap
# ============================================
log "Step 5: Disabling swap..."
swapoff -a

# Remove swap from fstab
sed -i '/swap/d' /etc/fstab 2>/dev/null || warn "Could not modify fstab"

# ============================================
# Step 6: Install RKE2 Agent
# ============================================
log "Step 6: Installing RKE2 agent..."
log "This may take a few minutes..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -

# ============================================
# Step 7: Configure RKE2 Agent
# ============================================
log "Step 7: Configuring RKE2 agent..."

mkdir -p /etc/rancher/rke2

# Create config file
cat <<EOF > /etc/rancher/rke2/config.yaml
# RKE2 Agent Configuration
# Generated by install-rke2-agent.sh

# Server connection
server: https://${SERVER_IP}:9345
token: ${TOKEN}

# Node configuration
node-name: "$(hostname)"
EOF

log "Configuration file created at /etc/rancher/rke2/config.yaml"

# ============================================
# Step 8: Enable and Start RKE2 Agent
# ============================================
log "Step 8: Enabling RKE2 agent service..."
systemctl enable rke2-agent.service

log "Starting RKE2 agent service..."
systemctl start rke2-agent.service

# ============================================
# Step 9: Wait for Agent to Register
# ============================================
log "Step 9: Waiting for agent to register with server..."
log "This may take 2-3 minutes..."

# Wait for agent to be running
sleep 30

# Check service status
AGENT_STATUS=$(systemctl is-active rke2-agent.service)
log "Agent service status: $AGENT_STATUS"

if [[ "$AGENT_STATUS" != "active" ]]; then
    error "RKE2 agent service failed to start. Check logs: journalctl -u rke2-agent -f"
fi

# ============================================
# Step 10: Configure User Environment
# ============================================
log "Step 10: Configuring user environment..."

# Add to ec2-user profile if it exists
if id "ec2-user" &>/dev/null; then
    USER_HOME="/home/ec2-user"
elif id "ubuntu" &>/dev/null; then
    USER_HOME="/home/ubuntu"
else
    USER_HOME="$HOME"
fi

# Add to bashrc (worker nodes typically don't need kubectl, but adding for convenience)
cat <<EOF >> ${USER_HOME}/.bashrc

# RKE2 configuration
export PATH=\$PATH:/var/lib/rancher/rke2/bin
EOF

chown $(stat -c '%U:%G' ${USER_HOME}) ${USER_HOME}/.bashrc 2>/dev/null || true

log "Added RKE2 environment to ${USER_HOME}/.bashrc"

# ============================================
# Step 11: Display Summary
# ============================================
echo ""
echo "=========================================="
log "RKE2 Agent Installation Complete!"
echo "=========================================="
echo ""
echo "Node Name:   $(hostname)"
echo "Server IP:   ${SERVER_IP}"
echo ""
echo "To verify on the server node:"
echo "  kubectl get nodes"
echo ""
echo "This node should appear as Ready in a few minutes."
echo ""
echo "To view agent logs:"
echo "  journalctl -u rke2-agent -f"
echo ""
